# Generated by Django 5.0.4 on 2024-04-08 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
                ('image', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'CakeType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
            ],
            options={
                'db_table': 'Characteristic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConcreateIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
                ('image', models.TextField(max_length=100)),
                ('image_ready', models.TextField(max_length=100)),
                ('Value', models.FloatField(blank=True)),
                ('Overlapping', models.BooleanField()),
                ('IsEssential', models.BooleanField()),
            ],
            options={
                'db_table': 'ConcreateIngredients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
                ('image', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'Ingredients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CICT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_cake_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.caketype')),
                ('Id_conc_ing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.concreateingredients')),
            ],
            options={
                'db_table': 'CICT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CIChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.TextField(max_length=100)),
                ('Id_char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.characteristic')),
                ('Id_conc_ing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.concreateingredients')),
            ],
            options={
                'db_table': 'CIChar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
                ('Id_cake_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.caketype')),
            ],
            options={
                'db_table': 'Dish',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DishIng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_conc_ing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.concreateingredients')),
                ('Id_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.dish')),
            ],
            options={
                'db_table': 'DishIng',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='concreateingredients',
            name='Id_ing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='diplom.ingredients'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(max_length=12)),
                ('customer_name', models.TextField(max_length=50)),
                ('order_date', models.DateField()),
                ('Id_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.dish')),
            ],
            options={
                'db_table': 'Order',
                'managed': True,
            },
        ),
    ]
