# Generated by Django 5.0.4 on 2024-04-12 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0003_rename_cict_ingct_remove_ingct_id_conc_ing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.characteristic')),
                ('Id_ing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.ingredients')),
            ],
            options={
                'db_table': 'IngChar',
                'managed': True,
            },
        ),
    ]
