# Generated by Django 5.0.4 on 2024-04-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0004_ingchar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concreateingredients',
            name='IsEssential',
        ),
        migrations.RemoveField(
            model_name='concreateingredients',
            name='Overlapping',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='IsEssential',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredients',
            name='Overlapping',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
