# Generated by Django 5.0.4 on 2024-04-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0005_remove_concreateingredients_isessential_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='Overlapping',
            new_name='IsVisible',
        ),
    ]
