# Generated by Django 5.0.4 on 2024-05-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0006_rename_overlapping_ingredients_isvisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='IsConstructed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishing',
            name='Location',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredients',
            name='IsConstruct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
