# Generated by Django 5.0.4 on 2024-05-22 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0007_dish_isconstructed_dishing_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='Id_cake_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diplom.caketype'),
        ),
    ]
