# Generated by Django 5.0.4 on 2024-05-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0008_alter_dish_id_cake_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='IsConstructed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='IsSaved',
            field=models.BooleanField(null=True),
        ),
    ]
