# Generated by Django 5.0.4 on 2024-05-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0011_remove_order_id_dish_orderdish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreateingredients',
            name='Id_ing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.ingredients'),
        ),
    ]
