# Generated by Django 5.0.4 on 2024-06-03 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0012_alter_concreateingredients_id_ing'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.user')),
            ],
            options={
                'db_table': 'Token',
                'managed': True,
            },
        ),
    ]
